### ISSUE TITLE
cloud.chainlit.io Oh no... Unexpected error bug

### ISSUE THREAD

**Issue by InfernalAzazel** [Chainlit/chainlit#11]
![微信截图_20230528121519](https://github.com/Chainlit/chainlit/assets/40333954/7b13cf05-973f-4afe-8a01-52094435099d)

**Comment by willydouhard** [comment]
Is this happening when creating the project?

I see an `InvalidCharacterError: Invalid character` error in the logs so I would be interested to get the project name you are trying to create.

**Comment by InfernalAzazel** [comment]
> Is this happening when creating the project?
> 
> I see an `InvalidCharacterError: Invalid character` error in the logs so I would be interested to get the project name you are trying to create.

I use Chinese for the project name

**Comment by willydouhard** [comment]
Can you try with a project using the latin alphabet to make sure this is the issue? If that is the case I will investigate to fix it :)

**Comment by InfernalAzazel** [comment]
> 您可以尝试使用拉丁字母的项目来确保这是问题所在吗？如果是这种情况，我将调查修复它 :)

I use Chinese for the project name e.g: 项目

My guess is that your database fields may use a specific encoding

Usually too many UTF-8 supports Chinese language display

**Comment by willydouhard** [comment]
I was able to reproduce. This is only problematic for the ID of the project. Because the ID is then used to generate cursors for pagination and this is where the error happens.

Since the ID of the project is derived from the name, please use the latin alphabet for the name of your project until we find a solution.
For the rest, you should be able to use chinese characters :)
