### ISSUE TITLE
Chainlit on docker not working after update to 1.1.404

### ISSUE THREAD

**Issue by developweblink** [Chainlit/chainlit#1312]
Chainlit on docker not working after update to 1.1.404

I have an EMPTY http error

Does anyone know if there are some breaking changes in 1.1.404?
rolling back to 1.1.402 fixed my problem

Regards

**Comment by AidanShipperley** [comment]
On the Chainlit Discord, they list the following breaking changes for 1.1.404:

- **[Breaking Change]** Chainlit now listens on 127.0.0.1 (localhost) instead of 0.0.0.0 (public) for improved security.

And more specifically:

- **Containerized Deployments**: If you're using containerized deployments, you may need to specify `--host 0.0.0.0` for your container to work correctly with the new security changes.

Have you tried making this change?

**Comment by dokterbob** [comment]
Check. Let me add it on GH to the release notes as well.

**Comment by MartinaRuocco** [comment]
Hey @dokterbob could you link here the updated release notes, please? 
Cheers xx

**Comment by MartinaRuocco** [comment]
Following this, I modified the last line of my Dockerfile from 

`CMD ["python", "-m", "chainlit", "run", "app.py", "-h", "--port", "8080"]`

to

`CMD ["python", "-m", "chainlit", "run", "app.py", "-h", "--port", "8080", "--host", "0.0.0.0"]`

✨ worked like a charm! ✨
Thank you!

**Comment by heydayYing** [comment]
I was able to docker build and up my chainlit container, but still my local browser still cannot connect to 0.0.0.0:8080. 
Virtual env works tho.
Here is my dockerfile, could anyone help pls:
`# Use the official python 3.9 image
FROM python:3.10-slim-bullseye

# Set the working directory to corrent folder
WORKDIR .

# Copy the requirements to working directory
COPY ./requirements.txt .

# Install all packages in requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

WORKDIR app/
COPY . /app

EXPOSE 8080

CMD ["python", "-m", "chainlit", "run", "model.py", "-h", "--port", "8080", "--host", "0.0.0.0"]

`
