### ISSUE TITLE
Allowed Origins not respected/working for web app

### ISSUE THREAD

**Issue by dqcloudadmin** [Chainlit/chainlit#1333]
**Describe the bug**

I have set the config value allow_origins to 2 https urls however the web app is still publicly accessible and the config values are not respected:

https://docs.chainlit.io/backend/config/project#options

```
# Authorized origins
allow_origins = ["https://xxxxxx.com","https://xxxxxxxxx.com"]
# (redacted urls)
```

I have set several features in the config which works fine but allow_origin does not work

**To Reproduce**

1. Set allow_origins to a url, restart app then try to access

**Expected behavior**

Access is blocked from urls outside the app

**Screenshots**

**Desktop (please complete the following information):**

- OS: Docker container 
- version: 1.1.402

**Additional context**

**Comment by dokterbob** [comment]
Thanks for the feedback! AFAIK, this is about CORS headers -- it's to allow API access from any rather than just the requesting site. In that case I would consider it a documentation bug, I would ask you fire a PR to change the docs. 

Please see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

That having been said, this value should _not_ be `*` by default. I've just created #1359 to keep track of that.

Do let me know if I didn't understand your question well or there's still doubt.
