### ISSUE TITLE
End user authentication for Cloud Run and custom endpoints.

### ISSUE THREAD

**Issue by fvaleye** [Chainlit/chainlit#135]
Hello 👋,

Thank you for this awesome application!

I would like to use [identity-platform authentication of Google](https://cloud.google.com/run/docs/tutorials/identity-platform?hl=en)  to only authorize internal users of my company using GCP.

Using FastAPI, I could easily add a method `jwt_authenticated()` to parse Authorization header to verify the user ID token.

Do you have any recommendation to implement this in Chainlit?

As a side notes, I'm also interested in providing custom API endpoints in FastAPI fo trigger the application not only from the UI. A simple workaround is fine if nothing is feasible atm.

Thank you!

**Comment by willydouhard** [comment]
Hello!

We are currently working on enabling enterprise to plug in their authentication system. I'll reach out to you to learn more about your use case.

**Comment by willydouhard** [comment]
Today's release `0.5.1` brings major improvements to authentication. [Here](https://docs.chainlit.io/cloud/authentication) is the docs. Let me know if that helps!

**Comment by rachidbch** [comment]
Thank you for your answer.
This isn't a entreprise use case but a personal project to discover what can be done with autonomous agent. 
I selected Chainlit because of it has a good time to POC. 

Please note that use case presented above holds even in a non-authenticated mono-user application.
When an event is triggered on a custom API endpoint how to send a message to the user?
