### ISSUE TITLE
Include a pandas dataframe element

### ISSUE THREAD

**Issue by tituslhy** [Chainlit/chainlit#1350]
**Is your feature request related to a problem? Please describe.**
Chainlit offers many elements that can be tagged to a message. I would like to suggest loading a pandas dataframe element because the response of LLMs can be made more neat with a table.

**Describe the solution you'd like**
Inclusion of a pandas dataframe element.

**Describe alternatives you've considered**
Streamlit has this feature https://docs.streamlit.io/develop/api-reference/data/st.dataframe

It would be great if chainlit has it too.

**Comment by hadarsharon** [comment]
Unfortunately you are not the first to have requested this feature. 
For now I can only suggest using something like this (assuming your dataframe is stored in a variable `df`):

```python
await cl.Message(
    content="Data Table",
    elements=[cl.Text(content=df.to_markdown(index=False), display="inline")],
).send()
```

I also believe native support for DataFrames should be added, just like in Streamlit, because Markdown tables don't look half as good and aren't interactive. 
I've also tried something similar with `df.to_html` and `language="html"` in the cl.Message element, but:

1. It requires rendering unsafe HTML which is a potential security concern 
2. Still doesn't look that nice, not like Streamlit at least

**Comment by desertproject** [comment]
I'm currently working on a draft pull request to implement this feature. The implementation will utilize the [MUI X Data Grid](https://mui.com/x/react-data-grid/) component. I'll update this issue with more details and a link to the PR once it's available for feedback.

**Comment by tituslhy** [comment]
Looks great!

**Comment by tituslhy** [comment]
Can I check if users can interact with the data frame like in streamlit - if they click the column name does it sort the data frame?

**Comment by desertproject** [comment]
> Can I check if users can interact with the data frame like in streamlit - if they click the column name does it sort the data frame?

Yes, users can interact with the data frame similarly to how they would in Streamlit, including clicking the column name to sort it. You can explore additional interactive features and functionalities in this library [here](https://mui.com/x/react-data-grid/#mit-license-free-forever).

**Comment by sundar-sarvam** [comment]
When will a tag for this release be made?
