### ISSUE TITLE
Chainlit context not found in unit tests for applications

### ISSUE THREAD

**Issue by dokato** [Chainlit/chainlit#1528]
**Describe the bug**
My unittests fails with:
```py
chainlit.context.ChainlitContextException: Chainlit context not found
```

**To Reproduce**

I have a function that generates chainlit text:

```py
def _generate_message_text(txt:str) ->cl.Text:
    return cl.Text(name="Message", content=f"message: {txt}", display="inline")
```

but any sort of unit test like here

```py
def test_generate_message_text():
    cl_text = _generate_message_text("cat")
    assert 1==1
```

results in an error as above. What is recommended way to write unittests for functions that generate chainlit objects?

**Expected behavior**
An easy way to unit test chainlit generation elements outside of contex, or easy mechanism to mock the context.

chainlit ver.: `1.0.200`

**Comment by dokterbob** [comment]
Hi @dokato, excellent question!

In our internal unit tests, we use a pytest fixture to create a ChainlitContext. https://github.com/Chainlit/chainlit/blob/ff26451ea41768f7e73e244412cef7a4e67632af/backend/tests/conftest.py#L56

I'd be very curious to learn whether and how you manage to use something similar to do testing of applications built with chainlit.

Lastly, I would strongly suggest you upgrade if you are offering a public-facing application. There's a lot of security issues in chainlit as well as the dependencies fixed in later releases.

**Comment by aharth** [comment]
See https://github.com/Chainlit/chainlit/issues/1450#issuecomment-2441715453.
