### ISSUE TITLE
Making root-path configurable 

### ISSUE THREAD

**Issue by yuezhaows** [Chainlit/chainlit#275]
similar with https://github.com/Chainlit/chainlit/issues/6

currently the root-path is not configurable.

make f/e use the configurable root-path
* Read from Envs.
* Read from Args

**Comment by ArthurJahn** [comment]
This would be really awesome. I'm building some apps to run on a single subdomain, and configuring a root-path per app would be great

**Comment by Italoalberto** [comment]
That's very necessary for the application Im working with right now. I hope we have it any day soon

**Comment by willydouhard** [comment]
Can you explain what the current behavior prevents you to do? That would be helpful.

**Comment by ArthurJahn** [comment]
The docs says that 

> "Currently, you have to serve your Chainlit app from the root of your domain/subdomain. This means that you can’t serve it from a subdirectory like example.com/my-app." 

So, I'd like to be able to serve the app from different base path, like setting a [base tag](https://html.com/tags/base/) or something.

**Comment by willydouhard** [comment]
Okay so this is a different issue. This issue is about running the chainlit run command from a different level than the app file level.

**Comment by ArthurJahn** [comment]
Ok, so I'll open another issue

**Comment by DBairdME** [comment]
Hi. This type of issue also occurs when I'm looking to use chainlit within Sagemaker Studio and using's it's Jupyter URL proxy to redirect traffic to the port.

e.g. an initial request can be sent to https://<id>.studio.ap-southeast-2.sagemaker.aws/jupyter/default/proxy/8505 URL where the base URL is Sagemaker and the proxy.

External dependencies (some CSS and the like) will be rendered, but the subsequent calls to then return 404 errors.
<img width="516" alt="urlissue" src="https://github.com/Chainlit/chainlit/assets/107909616/5e7eb826-4bc8-40ea-87f3-5bd5e50ed734">

Would it be possible to set something so that Chainlit allows requests to be sent to '/jupyter/default/proxy/8505' or similar so that the requests can be served as needed.
