### ISSUE TITLE
Are these available? / Feature Requests

### ISSUE THREAD

**Issue by fire17** [Chainlit/chainlit#386]
Hi there,
Super awesome project,
was wondering if you support the following:

- [Important] Thumbs Up / Thumbs Down (with Comment) interface, that we can collect data that can be used in our optimization/finetune pipeline
- Branching History - just like openai has, where you can edit your prompt (or request a re-submission) and keep track of all branches of the converstaion
- Web-Embedding Support - since you already made a nice interface, is there a way for you to generate a script that we can add to any website, which will add an ai-chat buttom, and open a mini chat interface. (Needs to know the current domain/url, and if user is logged in for history conservation)
- API, so i can programattically automate and test my models, and watch it go in the interface

Please let me know if any of these are available currently,
Thanks alot and all the best!

**Comment by fire17** [comment]
Anyone?

**Comment by willydouhard** [comment]
Was busy with the latest release, sorry for the delay!

- For Human Feedback, thumbs up/down are [already available](https://docs.chainlit.io/concepts/feedback). The comment feature is [in progress](https://github.com/Chainlit/chainlit/pull/321).
Branching History - This is not available yet, the reason is that Chainlit is framework agnostic. Doing this with langchain for instance is not possible, while you can do it with just open ai. We think this is a great feature but hard to implement for all frameworks.
Web-Embedding Support - Not yet, we are considering it
API - You can declare [custom API endpoints](https://docs.chainlit.io/concepts/customization/custom-endpoint) to call your agents. A python SDK to interact programmatically with your data is also available (documentation on its way)
