### ISSUE TITLE
[Feature] Internationalization (i18n) Support

### ISSUE THREAD

**Issue by fangyinc** [Chainlit/chainlit#486]
Hello. First off, thank you for the incredible work on [chainlit](https://github.com/Chainlit/chainlit). It has proven to be extremely valuable for our works.

As the user base for chainlit grows, there might be non-English speaking users who could benefit from using it. To make it more accessible to a global audience, I'd like to propose adding internationalization (i18n) support to chainlit.

**Proposed Solution:**
1. Integrate an i18n library/tool such as "react-i18next" to manage translations.
2. Refactor the existing codebase to make UI text elements translatable.
3. Add a language switcher to the UI, allowing users to select their preferred language.

I'm willing to help kickstart this process and contribute where necessary. Please let me know your thoughts, and if there's any way I can assist.

Although I'm not very knowledgeable about the frontend, I have tried implementing react-i18next in the current project. I've seen some preliminary positive results. I would be more than happy to contribute my code.

Thank you for considering this proposal.

**Comment by willydouhard** [comment]
I think this is a great idea and we definitely welcome contributions on this topic! I can assign this issue to you if want to take the lead on it.

**Comment by fangyinc** [comment]
> I think this is a great idea and we definitely welcome contributions on this topic! I can assign this issue to you if want to take the lead on it.

Please assign this to me.

**Comment by bbence84** [comment]
I would love to see chainlit supporting multiple languages. I am not really a react expert unfortunately. I'll try to look into how to do this, but I might not implement something according to best practice.

BTW if you guys have Github Copilot, it would be very interesting to see if it can successfully refactor your code so that it uses react-i18next without much manual work. :)

**Comment by bbence84** [comment]
I did a quick test for one file in GPT4, and it did a decent job, but maybe the paid Copilot does an even better job. :)

**Comment by willydouhard** [comment]
Would love to see it. You can open a draft PR if you want!

**Comment by fangyinc** [comment]
Hi @willydouhard @bbence84 , I have implemented part of it in my local project, but it has some problems, i18n can't work in components (I'm not very knowledgeable about the frontend).

**Comment by Tonywhitemin** [comment]
Hello @willydouhard  and everyone! I'm also a Taiwanese learning to use Chainlit. Since the current TA is designed for Asian users, I'd like to check if there's any way I can manually change the displayed text content from English to Traditional Chinese on the frontend page? (Such as the text on the toolbar like readme, Chat, +New chat, etc.) Thank you!

**Comment by willydouhard** [comment]
Right now this is not prioritised but we are opened to contributions to make it happen faster
