### ISSUE TITLE
is there any chance for independent developer to data persistence with google and amazon service limited

### ISSUE THREAD

**Issue by Mrfranken** [Chainlit/chainlit#569]
hi, I carefully read the doc you contributed. 
But Google and Amzon service in my country are limited, and I'm a independent developer with no company.
Do I have any chance or ways to make my data persistence?

Br

**Comment by willydouhard** [comment]
Would need more details on that one.

Are you referring to the platform [self hosting deployment](https://docs.chainlit.io/cloud/deployment) ? If so that platform is available to anyone [here](https://cloud.chainlit.io/) and self deployment is only intended for companies that have privacy requirements.

**Comment by Mrfranken** [comment]
yes, I mean self hosting deployment, but sorry, my network is limited can not visit your website.
I noticed you can provide docker for self hosting right? I'm not sure if I satisfy the requirements to use it.
Is it possible that the ordinary user can implement their "host" for data persistence? Many thx
