### ISSUE TITLE
Rate limiting the number of messages or conversations per user per time period

### ISSUE THREAD

**Issue by s-jse** [Chainlit/chainlit#703]
Is there a way to achieve a similar effect to `Flask-Limiter` (https://flask-limiter.readthedocs.io/en/stable/) with `Chainlit`?
As in either limit the number of times per a certain amount of time an IP address can send requests to the back-end?

**Comment by tpatel** [comment]
Not at the moment. Labelling this as enhancement request.

**Comment by Luttik** [comment]
Hi this issue is closed as not planned. But what is the best approach here? We are talking about providing end-points for relatively expensive calls, so abuse is a real concern here. Is there something when it comes to abuse prevention on the roadmap (either just documenting best practices, or implementing something in the core framework)?

(@NilsGolembiewski for reference)
