### ISSUE TITLE
why are you limiting the following packages?

### ISSUE THREAD

**Issue by chaimt** [Chainlit/chainlit#731]
why are you limiting the following packages?

httpx = ">=0.23.0,<0.25.0"
fastapi = ">=0.100,<0.109.0"

**Comment by pchalasani** [comment]
As I noted in #739 , This is blocking any project that has chainlit 1.0.200 from installing the ollama python sdk, which is currently extremely useful due to its recent OpenAI-compatible API support.

**Comment by willydouhard** [comment]
The fastapi limitation was removed not long ago, for httpx we had some issues, will need to look into it.

**Comment by cenkalti** [comment]
I think the issue with httpx is resolved because it uses the >= version specifier now.

However, pyproject.toml still uses the caret requirement for the FastAPI version.

https://github.com/Chainlit/chainlit/blob/efc2c78359e99bdacc5082468f93f1170085bf3e/backend/pyproject.toml#L29-L32

Because FastAPI uses 0 as its major version, ^0.110.1 resolves as (>=0.110.1, <0.111.0). According to semantic versioning, a major version of 0 is for initial development, and each version could have breaking changes.

FastAPI is pretty stable though. It's disappointing that they still use 0 as the major version. You can read their rationale here: https://fastapi.tiangolo.com/deployment/versions/

I suggest changing the FastAPI requirement to use the >= specifier, like it is done for httpx.

Let me know if you want a PR.

**Comment by cenkalti** [comment]
Hey, I can't mount Chainlit to my existing FastAPI project because the dependency specification on the FastAPI package is too strict. Would you consider relaxing it by specifying it as following?

```
fastapi = ">=0.110.1"
```

**Comment by dokterbob** [comment]
@cenkalti We'd like to be more flexible here but we are currently not able to provide support for multiple FastAPI versions. To address this, we should:

1. Have unit tests for backend functionality, for which #1134 is a starting point.
2. Run tests on a matrix of supported versions of dependencies, for which #1214 is a starting point.

For either one, we explicitly applaud any contributions and -- and we'll do our best to work towards this as soon as we can. Until then, supporting a range of versions of dependencies will imply that, sooner or later, a big chunk of users will run into unexpected issues as we are literally unable to test all the different versions.

I'd recommend, until we're there, you deploy into your app from a fork of chainlit wherein you make the necessary changes to your dependency.
