### ISSUE TITLE
Investigate and fix file watcher issues

### ISSUE THREAD

**Issue by tpatel** [Chainlit/chainlit#790]
Related issues:

- https://github.com/Chainlit/chainlit/issues/655
- https://github.com/Chainlit/chainlit/issues/745
- https://github.com/Chainlit/chainlit/issues/784

**Comment by ddnovikov** [comment]
@tpatel I think I have a hint on this one -- bytecode is at least a part of the issue. Reloading doesn't work with `__pycache__` files being present. This is fixed by:
- Removing all bytecode folders in the project: `find . -type d -name "__pycache__" -exec rm -r {} +`.
- Setting `PYTHONDONTWRITEBYTECODE=1` environment variable.
