### ISSUE TITLE
Frontend/react-client does not resume session after backend connection loss

### ISSUE THREAD

**Issue by jbeckerdm** [Chainlit/chainlit#828]
**Describe the bug**
We use a chainlit setup with chat_persistence and on_chat_resume.
If we start a chat with one message, then cause a websocket disconnect by, for example, restarting the backend,
and then write another message once the reconnect happened, both messages will be persisted in two different sessions.
This can be reproduced with the integrated chainlit frontend.

**To Reproduce**
1. Start a chainlit backend on version ^1.0.301
2. Open the frontend on localhost:8000
3. Start a new chat by writing a message, say "message 1"
4. Stop and restart the backend process
5. Switch back to the frontend and wait for the "Could not reach the server" message to disappear.
6. Write a new message, say "message 2"
7. Reload the page and notice how there are two chats with one message each.

**Expected behavior**
There should be one persisted chat session with both messages in it

**Screenshots**
<img width="961" alt="Screenshot 2024-03-19 at 15 35 24" src="https://github.com/Chainlit/chainlit/assets/159531505/1e6f2204-851c-4b94-a283-cdfc3d30a195">

<img width="261" alt="Screenshot 2024-03-19 at 15 35 32" src="https://github.com/Chainlit/chainlit/assets/159531505/f2b5a61e-378e-4d12-b6ed-2f5af2dda57a">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 122

**Comment by qtangs** [comment]
I face this error too. This happens frequently for Cloud-hosted servers with auto-scaling.

I've traced the root cause to this:

- When server restarts, frontend requests a new websocket session with `X-Chainlit-Thread-Id` header (code below). But this header is empty because `idToResume` is never set for new threads. 
https://github.com/Chainlit/chainlit/blob/d9fa5ba50eae0f20ce9d1a140998f9a9fb2ec92f/libs/react-client/src/useChatSession.ts#L90
     `idToResume` is only set when a thread is resumed:
https://github.com/Chainlit/chainlit/blob/d9fa5ba50eae0f20ce9d1a140998f9a9fb2ec92f/frontend/src/pages/ResumeButton.tsx#L29
- Due to this, backend creates a new thread and ignore the existing messages completely (because the old thread is not loaded).


Possible solutions:
- In order to fix this I think we need to set `idToResume` for new threads after first user interaction.
    Building on this PR https://github.com/Chainlit/chainlit/pull/923, `idToResume` should be set here along with `currentThreadId`:
https://github.com/Chainlit/chainlit/blob/d9fa5ba50eae0f20ce9d1a140998f9a9fb2ec92f/libs/react-client/src/useChatSession.ts#L156
- Alternatively, the code in [useChatSession.ts](https://github.com/Chainlit/chainlit/blob/d9fa5ba50eae0f20ce9d1a140998f9a9fb2ec92f/libs/react-client/src/useChatSession.ts#L90) can be updated to:
```'X-Chainlit-Thread-Id': idToResume || currentThreadId || '', ```

@tpatel, what do you think? I can open a new PR for this fix.

**Comment by qvalentin** [comment]
@qtangs, my analysis of the problem found the same root cause. However, I don't think your suggested solutions will work.
The problem is that the `X-Chainlit-Thread-Id` value is given to the socket.io session when the session is created and cannot be updated later. So even if you use `setIdToResume(threadId!); ` the session will still have the same values for the headers.
When the server restarts, socket.io will retry the connection using the existing headers.

A possible solution would be to listen on the `reconnect` or `reconnect_attempt` event of socket.io and create a new session, if `idToResume` is not set.

**Comment by qtangs** [comment]
@qvalentin you're right. Using `currentThreadId` like that won't work as the initial value is undefined and the connection headers are not updated after the initial socket initialization.

I've tested this addition of the update after [useChatSession.ts#L68](https://github.com/Chainlit/chainlit/blob/923da0d9ef77822de4cd0c89c9e593783327e166/libs/react-client/src/useChatSession.ts#L68) and verified that it works:

```
  const idToResume = useRecoilValue(threadIdToResumeState);
  const setCurrentThreadId = useSetRecoilState(currentThreadIdState);

  // Use currentThreadId as thread id in websocket header if it's set
  const currentThreadId = useRecoilValue(currentThreadIdState);

  useEffect(() => {
    if (session?.socket && currentThreadId) {
        session.socket.io.opts.extraHeaders!['X-Chainlit-Thread-Id'] = currentThreadId;
    }
  }, [currentThreadId]);
```

**Comment by qvalentin** [comment]
Great, will you open a PR?

**Comment by willydouhard** [comment]
Please submit a PR!

**Comment by qtangs** [comment]
> Please submit a PR!

PR is created, pls review.

**Comment by deepakjyadav01** [comment]
Hey, just wanna know. is it fixed? I was facing a similar issue related to X-Chainlit-Thread-id being not set properly even after using clear(), using setIdtoResume() while resuming to the old chat?. What will be the best way of doing so. The values are getting updated if i refresh it but not when i set it before making reconnection. Any help??

**Comment by nguyenvanson1998** [comment]
> What will be the best way of doing so. The values are getting updated if i refresh it but not when i set it before making reconnection. Any help??

Have you done  fix this bug

**Comment by deepakjyadav01** [comment]
I thought they fixed it in the newer versions. I had a little workaround to make it work instead of getting any help from them. let me know if you wanna know

**Comment by nguyenvanson1998** [comment]
> I thought they fixed it in the newer versions. I had a little workaround to make it work instead of getting any help from them. let me know if you wanna know

Yeah. I am currently using react-client version 0.2.4 however it still have this bug. Can you tell me your solution and example to fix it. Thank you very much

**Comment by deepakjyadav01** [comment]
### Solution Overview

To ensure that every time you switch threads the X-Chainlit-Thread-Id header is correctly set on your WebSocket connection—without relying on a buggy “soft reconnect” . you can force React to completely tear down and recreate your <Chat> component. React does this automatically whenever a component’s key prop changes. By:

- Keeping a simple counter in state (chatKey).
- Incrementing it each time the user switches threads.
- Passing it as the key on <Chat>…
- React will unmount the old chat (closing its socket) and mount a brand-new one (creating a fresh socket with the right header).

tsx
```
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import { useState } from "react";
import Sidebar from "./components/Sidebar";
import Chat from "./components/Chat"; // Handles chainlit session and socket logic

function App() {
  // 1. chatKey holds a simple “remount token”
  const [chatKey, setChatKey] = useState(0);

  // 2. Whenever we want to switch threads, bump the token
  const handleThreadSwitch = () => {
    setChatKey(prevKey => prevKey + 1);
  };

  return (
    <BrowserRouter>
      <div className="flex">
        {/* Tell Sidebar to call this when the user clicks a new thread */}
        <Sidebar onThreadSwitch={handleThreadSwitch} />

        <div className="flex-1">
          <Routes>
            {/* 3. Pass chatKey as the React “key” prop */}
            <Route
              path="/chat/:threadId"
              element={<Chat key={chatKey} />}
            />
            <Route
              path="/chat/newchat"
              element={<Chat key={chatKey} />}
            />
            <Route path="/" element={<Navigate to="/chat/newchat" />} />
          </Routes>
        </div>
      </div>
    </BrowserRouter>
  );
}

export default App;
```
### **Code Breakdown**
const [chatKey, setChatKey] = useState(0);

Initializes a numeric state variable. It doesn’t represent anything in your domain model—it’s purely a “token” that React uses to decide whether to reuse or recreate <Chat>.

handleThreadSwitch()

When the user selects a different thread in your <Sidebar>, you call setChatKey(prev => prev + 1). This guaranteed change in chatKey will signal React that the next <Chat> is “new.”

key={chatKey} on <Chat>

React’s reconciliation algorithm sees that the key changed:

Old key? Reuse component.

New key? Unmount the old component (runs its cleanup, including closing the old socket) and mount a fresh instance.

Fresh mount = fresh socket handshake

On mount, your <Chat> reads :threadId from the URL and sets up the Chainlit WebSocket. Because it’s a brand-new socket (not a “soft reconnect”), it sends X-Chainlit-Thread-Id correctly every time.

I can't give more details than this due to the privacy of this project. I hope you can get the idea of what the issue was and instead of them(chainlit) refreshing it we do it manually with the help of react features like a basic counter that will update as soon as you receive a new value. This was a little workaround but this is something they were missing
