### ISSUE TITLE
Chainlit.cli has “IndentionError : unindent doesn’t match any outer infection level” on dataclass_json/api.py on line 141

### ISSUE THREAD

**Issue by saikumar-123** [Chainlit/chainlit#854]
**Describe the bug**

Chainlit.cli has “IndentionError : unindent doesn’t match any outer infection level” on dataclass_json/api.py on line 143

**Expected behavior**
Chainlit to startup on kubernetes 

**Screenshots**
Attached[]()![image](https://github.com/Chainlit/chainlit/assets/10671793/f6396e33-f72a-4814-9cef-452a62adf068)

**Comment by dahifi** [comment]
Can you verify this with 3.11? That looks like a dependency error. 

A dump of installed packages would be useful here, my poetry.lock has `dataclasses_json = ">=0.5.7,<0.6.0"`.

**Comment by saikumar-123** [comment]
I was using python:3.10-slim-bookworm because of the sqlelite3 issue on python:3-11-slim-buster.


One thing I noticed was on poetry install. 
![image](https://github.com/Chainlit/chainlit/assets/10671793/816afacc-be39-45d6-a735-fbb293435983)

**Comment by dahifi** [comment]
Yea I recall seeing that during a docker build myself, but can't replicate with the import. 

By the way, you're importing the whole module instead of the data class. Maybe try `from chainlit.input_widget import InputWidget` instead? 

Make sure you're running most recent version of CL also. 401 is the latest.
