### ISSUE TITLE
How to run integration test for a chainlit app

### ISSUE THREAD

**Issue by tjroamer** [Chainlit/chainlit#880]
I'd like to run an integration test for my chainlit app with the pytest framework with the following requirements to make sure the app is not broken:

- I want to define a test module, test_app in a tests folder
- in the test module, I first start the chainlit app
- I send a message to the app by calling a function
- I got a response message from the app and verify the response
- But I don't want to UI in the browser during the test, just want the app running in the background

Could anyone give me some ideas? Thanks in advance.

**Comment by dividor** [comment]
I have set this up in a rather hokey way by monkey-patching the chainlit class. It's not pretty, and debatable whether it's really testing the app fully, but satisfies some scenarios for me. I am testing in Github actions using promptflow where I want to test how workflows branch in my chainlit app. I don't think my awful hack terribly sustainable to be honest and I'm not proud of it, but here goes ... 

First, I created a mock class, which replicates many of the main functions in a chainlit app. [See here](https://github.com/datakind/data-recipes-ai/blob/feat/pf-tests-v2/flows/chainlit-ui-evaluation/call_assistant.py#L87).

Then in my wrapper which calls the code in my chainlit app, I use the mock class to patch chainlit and call functions in my app without having to make and code changes to the app. [See here](https://github.com/datakind/data-recipes-ai/blob/feat/pf-tests-v2/flows/chainlit-ui-evaluation/call_assistant.py#L441).

It works nicely, apart from the fact the function doesn't exist due to some hanging async thread which I couldn't get to the bottom of in the short time I had to work on this. In my eternal, unmitigated shame, I wrapped it in a call which monitors output then kills the process. YUK!!!! This is just awful, with some more time I'll go back and figure this out.

Please don't accept this answer, only posting it in case it inspires more adept folks than I to point us at a more formal way to do this.
